name: Build & Release 567.901

on:
  release:
    types: [created]

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install tectonic
        run: |
          sudo apt-get update
          sudo apt-get install -y tectonic
      - name: Build 567.901 PDF
        run: |
          tectonic -o papers/567.901 papers/567.901/FRC_567_901_Resonance_Maximization_Report.tex
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            papers/567.901/FRC_567_901_Resonance_Maximization_Report.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
